services:
    chat:
        build:
            context: .
            dockerfile: ./docker/php.dockerfile
        container_name: chat
        restart: unless-stopped
        volumes:
            - .:/var/www
        networks:
            - chat_network
        depends_on:
            - postgres
        ports:
            - "9000:80"
    #        command: >
    #            sh -c "php artisan reverb:start && php artisan queue:listen"
    postgres:
        image: postgres
        container_name: chat_psg
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - chat_network
        ports:
            -   "5431:5431"  # Expose PostgreSQL on port 5432
    pgadmin:
        image: dpage/pgadmin4
        container_name: chat_pgadmin1
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "8081:80"
        networks:
            - chat_network
    nginx:
        container_name: chat_nginx1
        image: nginx:alpine # Use the Nginx image
        ports:
            - "9000:80"  # Map port 8080 on the host to port 80 inside the container
        volumes:
            - ./:/var/www  # Mount the Laravel chat_application directory-
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf  # Use our Nginx config
        depends_on:
            - chat  # Ensure PHP-FPM is started before Nginx
        networks:
            - chat_network  # Connect to the custom network
    node:
    
        image: node:22
        container_name: chat_node1
        working_dir: /var/www
        volumes:
            - ./:/var/www
        tty: true
        ports:
            - "5173:5173"  # For Vite development server
        environment:
            - NODE_ENV=development
        command: >
            sh -c "npm install && npm run dev"
        networks:
            - chat_network

    redis:
        image: redis:latest
        container_name: websocket_redis1
        ports:
            - "1234:4321"
        volumes:
            - redis-data:/data
        networks:
            - chat_network

volumes:
    postgres_data:
    redis-data:

networks:
    chat_network:
        driver: bridge